### ISSUE TITLE
The gitea username may notbe the integration_id from canvas

### ISSUE THREAD

**Issue by wznmickey** [BoYanZh/Joint-Teapot#25]
There are some students whose gitea username is not the integration_id on the canvas system. So we can not do any operation on the account of these students.
I searched api of gitea. It seems that we can not get the username by email. 
Is it possible to store a dict that we can store the relationship from integration_id to username by hand and use them later?

**Comment by BoYanZh** [comment]
Do you have an example of it? I can check gitea for the reason or fix gitea.

**Comment by wznmickey** [comment]
https://focs.ji.sjtu.edu.cn/git/gxy0422

**Comment by BoYanZh** [comment]
All fixed now.
