### ISSUE TITLE
Configuring suffix for create-webhooks-for-mm

### ISSUE THREAD

**Issue by mQzLjP** [BoYanZh/Joint-Teapot#42]
Is there a way to extract and add the suffix in this method, so that I can link gitea repo `aaaa-p1` with MM channel `aaaa-git`? I think that would be more useful than the current usage of linking repos and channels only with the same name.

**Comment by BoYanZh** [comment]
I have little knowledge about mattermost.
But if it is not in the script right now, you can write your own code just like https://github.com/BoYanZh/Joint-Teapot/blob/master/examples/ve482.py.
